---
-
  become: true
  hosts: 192.168.1.17
  name: "DHCP Configuration"
  tasks:
  
    - name: Setting up Dynamic IP 
      replace:
        path: /var/ftp/pub/ks.cfg
        regexp: '^(network.+)$'
        replace: 'network  --bootproto=dhcp --device=ens192 --onboot=off --ipv6=auto --no-activate --hostname={{ VM_NAME }}'

    - name: Restarting services now
      service:
        name: "{{ item.services }}"
        state: restarted
      with_items:
        - { services: 'dnsmasq' }
        - { services: 'vsftpd' }
