--- 
- 
  become: true
  hosts: 192.168.1.17
  name: "Pxe automation"
  tasks: 

    - name: adding user and passwrd
      replace:
        path: /root/test
        regexp: '^(default[ ]+)[^\n]+$'
        replace: '\g<1>{{ NUM }}'
