--- 
- 
  become: true
  hosts: 192.168.1.17
  name: "Kick-Start file"
  tasks: 

    - name: Selecting Kick- Start file for imaging
      replace:
        path: /var/lib/tftpboot/pxelinux.cfg/default
        regexp: '^(default[ ]+)[^\n]+$'
        replace: '\g<1>{{ OS_image }}'
